repos:
- repo:  https://github.com/pre-commit/pre-commit-hooks.git
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-xml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']
  - id: name-tests-test
    args: ["--pytest-test-first"]
  - id: pretty-format-json
    args: [--autofix, --indent, "4"]
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: ['PyYAML']

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "v2.5.0"
  hooks:
    - id: pyproject-fmt
