version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - pandoc
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
sphinx:
  configuration: docs/source/conf.py
