version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - pandoc
    - g++14
    - pkg-config
    - liblapacke-dev
  jobs:
    post_checkout:
      - git fetch --tags
      - git fetch --unshallow
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
        - testing
sphinx:
  configuration: docs/source/conf.py
