import os
env = Environment()

env['CXX']      = 'g++'
env['CPPPATH']  = ['../include']
env['LIBS']     = ['gsl' , 'gslcblas','hdf5','hdf5_hl']
env['CPPFLAGS'] = ['-std=c++14', '-O3']
 
sources = ['FluxInspiral.cc', 'Interpolant.cc', 'SpinWeightedSphericalHarmonics.cc']

env.Program('../FluxInspiral', sources)