name: test_install_env
channels:
  - conda-forge

dependencies:
  - python
  - openblas 
  - lapack 
  - liblapacke
  - wget
  - hdf5
  - numpy
  - scipy
  - Cython
  - tqdm
  - jupyter
  - ipython
  - h5py
  - requests
  - matplotlib
  - numba
  - rich
  - clang_osx-arm64
  - clangxx_osx-arm64